/*
Seth Amico, John Teal
UW TCES 330
Programmable Processor
Project File: Processor.sv
10 June 2026
*/

`timescale 1ns/1ps
module Processor(
    input Clk,
    input ResetN,

    output [15:0] IR_Out,
    output [6:0] PC_Out,
    output [3:0] State,
    output [3:0] NextState,

    output [15:0] ALU_A,
    output [15:0] ALU_B,
    output [15:0] ALU_Out
);

    /*
    The provided testProcessor.sv uses active-low reset. ResetN = 0 means reset is active.
    ResetN = 1 means normal processor operation. The internal Control Unit/FSM uses active-high 
    reset, so ResetN is inverted here.
    */
    wire Reset;

    assign Reset = ~ResetN;

    /*
    The PC module and Control Unit use an 8-bit PC internally. The provided testProcessor.sv 
    expects PC_Out to be 7 bits because the ROM is 128 words and uses address[6:0].
    */
    wire [7:0] PC_Out_full;

    assign PC_Out = PC_Out_full[6:0];

    /*
    Control signals from the Control Unit to the Datapath. These internal wire names 
    intentionally use the capitalization expected by testProcessor.sv. The testbench monitors 
    DUT.RF_Ra_Addr directly.
    */
    wire [7:0] D_Addr;
    wire D_wr;

    wire RF_s;

    wire [3:0] RF_W_Addr;
    wire RF_W_en;

    wire [3:0] RF_Ra_Addr;
    wire [3:0] RF_Rb_Addr;

    wire [2:0] Alu_s0;

    /*
    ALU flag wires. These flags are generated by the Datapath and passed to the Control Unit
    for conditional jump instructions.
    */
    wire Alu_Z;
    wire Alu_N;
    wire Alu_V;

    // Control Unit instance.
    Control_Unit control0(
        .Clk(Clk),
        .rst(Reset),

        .Alu_Z(Alu_Z),
        .Alu_N(Alu_N),
        .Alu_V(Alu_V),

        .D_Addr(D_Addr),
        .D_wr(D_wr),

        .RF_s(RF_s),

        .RF_W_addr(RF_W_Addr),
        .RF_W_en(RF_W_en),

        .RF_Ra_addr(RF_Ra_Addr),
        .RF_Rb_addr(RF_Rb_Addr),

        .Alu_s0(Alu_s0),

        .IR_Out(IR_Out),
        .PC_Out(PC_Out_full),
        .StateOut(State),
        .NextStateOut(NextState)
    );

    // Datapath instance.
    Datapath datapath0(
        .Clk(Clk),

        .D_Addr(D_Addr),
        .D_wr(D_wr),

        .RF_s(RF_s),
        .RF_W_en(RF_W_en),

        .RF_Ra_addr(RF_Ra_Addr),
        .RF_Rb_addr(RF_Rb_Addr),
        .RF_W_addr(RF_W_Addr),

        .Alu_s0(Alu_s0),

	.ALU_A(ALU_A),
	.ALU_B(ALU_B),
	.ALU_Out(ALU_Out),

	.Alu_Z(Alu_Z),
	.Alu_N(Alu_N),
	.Alu_V(Alu_V)
    );
endmodule

module Processor_tb();

    logic Clk;
    logic ResetN;

    logic [15:0] IR_Out;
    logic [6:0] PC_Out;
    logic [3:0] State;
    logic [3:0] NextState;

    logic [15:0] ALU_A;
    logic [15:0] ALU_B;
    logic [15:0] ALU_Out;

    integer i;
    integer pass_count;
    integer fail_count;

    logic saw_store;
    logic saw_halt;

    localparam [3:0] S_STORE = 4'd4;
    localparam [3:0] S_HALT  = 4'd9;

    Processor dut(
    	.Clk(Clk),
    	.ResetN(ResetN),

    	.IR_Out(IR_Out),
    	.PC_Out(PC_Out),
    	.State(State),
    	.NextState(NextState),
	
    	.ALU_A(ALU_A),
    	.ALU_B(ALU_B),
    	.ALU_Out(ALU_Out)
    );

    initial Clk = 1'b0;

    always begin
        #5 Clk = ~Clk;
    end

    task automatic tick;
        begin
            @(posedge Clk);
            #1;
        end
    endtask

    task automatic check1;
        input [255:0] name;
        input actual;
        input expected;

        begin
            if (actual === expected) begin
                pass_count = pass_count + 1;
            end else begin
                fail_count = fail_count + 1;
                $display("FAIL: %0s expected=%b actual=%b time=%0t",
                         name, expected, actual, $time);
            end
        end
    endtask

    task automatic check16;
        input string name;
        input [15:0] actual;
        input [15:0] expected;

        begin
            if (actual === expected) begin
                pass_count = pass_count + 1;
            end else begin
                fail_count = fail_count + 1;
                $display("FAIL: %0s expected=%h actual=%h time=%0t",
                         name, expected, actual, $time);
            end
        end
    endtask

    initial begin
        pass_count = 0;
        fail_count = 0;

        saw_store = 1'b0;
        saw_halt  = 1'b0;

        ResetN = 1'b0;

        $display("Starting Processor testbench.");

        // Hold reset for two clock edges so the control unit starts cleanly.
        tick();
        tick();

        ResetN = 1'b1;

        for (i = 0; i < 50; i = i + 1) begin
            tick();

            $display("cycle=%0d PC=%h IR=%h State=%0d Next=%0d ALU_A=%h ALU_B=%h ALU_Out=%h D_Addr=%h D_wr=%b",
                     i, PC_Out, IR_Out, State, NextState, ALU_A, ALU_B, ALU_Out,
                     dut.D_Addr, dut.D_wr);

	/*
	The ROM/RAM test program should eventually execute: 
	D[6A] = D[1B] - D[2A] + D[3C] - D[7E]
	D[6A] = 21BA - A04E + 71AC - B17F = 4199
	During STORE, D_wr should be high, D_Addr should be 6A, and ALU_A should contain 4199.
	*/
            if ((State == S_STORE) && (dut.D_wr == 1'b1) && (dut.D_Addr == 8'h6A)) begin
                saw_store = 1'b1;
                check16("STORE value from RF[A]", ALU_A, 16'h4199);
            end

            if (State == S_HALT) begin
                saw_halt = 1'b1;
            end
        end

        check1("Processor reached STORE", saw_store, 1'b1);
        check1("Processor reached HALT", saw_halt, 1'b1);
        check16("Final IR should be HALT", IR_Out, 16'h5000);

        $display("Processor testbench complete.");
        $display("Passes: %0d", pass_count);
        $display("Failures: %0d", fail_count);

	if (fail_count == 0) begin
	    $display("RESULT: PASS");
	end
	else begin
	    $display("RESULT: FAIL");
	end

        $finish;
    end

endmodule
